



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Centre_Cours_Soutien_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

server:
  port: 5052
